// File generated by FlutterFire CLI & Antigravity Assistant.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return ios;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_csse_study_hub_web_key_placeholder',
    appId: '1:100000000000:web:csse_study_hub_web_appid',
    messagingSenderId: '100000000000',
    projectId: 'csse-study-hub-prod',
    authDomain: 'csse-study-hub-prod.firebaseapp.com',
    storageBucket: 'csse-study-hub-prod.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_csse_study_hub_android_key_placeholder',
    appId: '1:100000000000:android:csse_study_hub_android_appid',
    messagingSenderId: '100000000000',
    projectId: 'csse-study-hub-prod',
    storageBucket: 'csse-study-hub-prod.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_csse_study_hub_ios_key_placeholder',
    appId: '1:100000000000:ios:csse_study_hub_ios_appid',
    messagingSenderId: '100000000000',
    projectId: 'csse-study-hub-prod',
    storageBucket: 'csse-study-hub-prod.appspot.com',
    iosBundleId: 'com.csse.studyhub',
  );
}
