// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjxr0XIyJAMBDMDlk8kFnfzuW6QpGbkVU',
    appId: '1:88359315332:web:e0a7f4dac670e0583e9fd1',
    messagingSenderId: '88359315332',
    projectId: 'unidocs-study-hub',
    authDomain: 'unidocs-study-hub.firebaseapp.com',
    storageBucket: 'unidocs-study-hub.firebasestorage.app',
    measurementId: 'G-TTWXVGHNVM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5l9oFMJgLId8Aet1vsq-fW07wcKlYwKc',
    appId: '1:88359315332:android:48f2e7a63ab76e123e9fd1',
    messagingSenderId: '88359315332',
    projectId: 'unidocs-study-hub',
    storageBucket: 'unidocs-study-hub.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjxr0XIyJAMBDMDlk8kFnfzuW6QpGbkVU',
    appId: '1:88359315332:ios:48f2e7a63ab76e123e9fd1',
    messagingSenderId: '88359315332',
    projectId: 'unidocs-study-hub',
    storageBucket: 'unidocs-study-hub.firebasestorage.app',
    iosBundleId: 'com.csse.studyhub.csseStudyHub',
  );
}
