// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIIIFgpy7T1q3LWez8E9H3EARqGkCNdxg',
    appId: '1:559967220631:web:4bef765223aba5f808cad2',
    messagingSenderId: '559967220631',
    projectId: 'my-unidocs-app',
    authDomain: 'my-unidocs-app.firebaseapp.com',
    storageBucket: 'my-unidocs-app.firebasestorage.app',
    measurementId: 'G-KWKC7822NN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-IhXlcN-MZ8X0x6AA-bSa14tuGST-yHk',
    appId: '1:559967220631:android:acd55572f9cc3a1d08cad2',
    messagingSenderId: '559967220631',
    projectId: 'my-unidocs-app',
    storageBucket: 'my-unidocs-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdLh_5nGNSYL3cS9lo9TBUmXpUuK5Gmh4',
    appId: '1:559967220631:ios:ade8a3cdacf0451008cad2',
    messagingSenderId: '559967220631',
    projectId: 'my-unidocs-app',
    storageBucket: 'my-unidocs-app.firebasestorage.app',
    iosBundleId: 'com.csse.studyhub.csseStudyHub',
  );
}
